services:
    ady.changecover.controller:
        class: ady\changecover\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '%core.table_prefix%'